#:schema node_modules/wrangler/config-schema.json
name = "pg-idna-docs"
compatibility_date = "2024-11-06"
assets = { directory = "./public" }

# Workers Logs
# Docs: https://developers.cloudflare.com/workers/observability/logs/workers-logs/
# Configuration: https://developers.cloudflare.com/workers/observability/logs/workers-logs/#enable-workers-logs
[observability]
enabled = true
